management:
    endpoints:
        web:
            exposure:
                include: "health, metrics, prometheus, info"
    endpoint:
        health:
            show-details: always
            probes:
                add-additional-paths: true
        env:
            show-values: never
    info:
        env:
            enabled: true
        java:
            enabled: true
        os:
            enabled: true
    zipkin:
        tracing:
            endpoint: "${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}"

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                - id: zipkin
                  uri: http://openzipkin.dashaun-io.svc.cluster.local:9411
                  predicates:
                      - Path=/zipkin/**
                - id: root
                  uri: https://javagrunt.github.io
                  predicates:
                      - Path=/**
    config:
        import: "optional:configserver:"
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            password: ${REDIS_PASSWORD:}
            port: ${REDIS_PORT:6379}
            username: ${REDIS_USERNAME:}
    main:
        web-application-type: reactive
    threads:
        virtual:
            enabled: true